In [ ]:
import numpy as np

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
B = [[16, 8, 2, 4], [5, 7, 8, 11], [20, 30, 40, 50]]
C = np.array([[1, 2, 3], [3, 4, 5]])
D = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 8, 9], [8, 7, 7, 8], [4, 5, 9, 8]]
print(A)
print(B)
print(C)
print(D)


[[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
[[16, 8, 2, 4], [5, 7, 8, 11], [20, 30, 40, 50]]
[[1 2 3]
 [3 4 5]]
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 8, 8, 9], [8, 7, 7, 8], [4, 5, 9, 8]]


In [ ]:
## A)
X = A
for i in range(len(X)):
  for j in range(len(X[i])):
    print(A[i][j], end=' ')
print()
X = B
for i in range(len(X)):
  for j in range(len(X[i])):
    print(X[i][j], end=' ')
print()
X = C
for i in range(len(X)):
  for j in range(len(X[i])):
    print(X[i][j], end=' ')
print()
X = D
for i in range(len(X)):
  for j in range(len(X[i])):
    print(X[i][j], end=' ')
print('\n')

## B)
x2 = np.random.randint(10, size=(3, 4))
print(x2[:, 0])
print(x2[0,:])
print(x2[0:2, 2:3])
A4 = x2
print(A4)
A4[: ,0] = 0
print(A4)
A5 = x2[-1,-1]
print(A5)
A6 = x2[: , -1]
print(A6)
A7 = x2[-1, -2]
print(A7)
A9 = np.transpose(x2)
print(A9)

print('\n')

## C)
C1 = np.array(range(0,21))
print(C1)
C2 = np.array(range(0,21,2))
print(C2)
C3 = np.array(range(1,21,2))
print(C3)
C4 = np.arange(0.0,1.1,0.1)
print(C4)

1 4 5 12 -5 8 9 0 -6 7 11 19 
16 8 2 4 5 7 8 11 20 30 40 50 
1 2 3 3 4 5 
1 2 3 4 5 6 7 8 9 8 8 9 8 7 7 8 4 5 9 8 

[5 4 8]
[5 8 1 0]
[[1]
 [4]]
[[5 8 1 0]
 [4 3 4 9]
 [8 7 9 9]]
[[0 8 1 0]
 [0 3 4 9]
 [0 7 9 9]]
9
[0 9 9]
9
[[0 0 0]
 [8 3 7]
 [1 4 9]
 [0 9 9]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
x2 = np.random.randint(10, size=(3, 4))
print(x2)
M1 = np.sum(x2)
print(M1)
M1 = x2.max(axis=0)
print(M1)
M2 = np.max(x2)
print(M2)
M3 = x2.min(axis=0)
print(M3)
M4 = np.min(x2)
print(M4)
print()
M5 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(M5)
M6 = M5[0:-1, 0:3]
print(M6)

[[7 3 4 7]
 [4 4 2 5]
 [1 7 4 2]]
50
[7 7 4 7]
7
[1 3 2 2]
1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
